version: '2'
# we can use docker-compose style services: (see https://docs.docker.com/compose/compose-file/ for docs)
#
services:
   teleport:
      image: cartman640/teleport
      volumes:
         - "drunner-config:/config"
      restart: always
      ports:
        - "3023:3023"
        - "3024:3024"
        - "3025:3025"
        - "3080:3080"
      network_mode: bridge

# we manage services manually in servicerunner, so there's no services
# section.

# if we don't want to use dRunner's environment variables for our
# configuraiton we should reinstate the config volume with this.
#
volumes:
  drunner-config:
     external:
        name: "drunner-${SERVICENAME}-config"
